"""Compile checked-in translations into a local, integrity-pinned script."""
from pathlib import Path
import json
ROOT=Path(__file__).resolve().parents[1]
source=json.loads((ROOT/'scripts/locale-source.json').read_text(encoding='utf-8'))
rows=[line.split('|') for line in (ROOT/'scripts/locale-rows.tsv').read_text(encoding='utf-8').splitlines() if line]
assert len(rows)==len(source)
catalog={}
for i,row in enumerate(rows):
 assert int(row[0])==i and len(row)==6,(i,row)
 catalog[source[i]]=['ru',*row[1:]]
 catalog[source[i]][0]=source[i]
for line in (ROOT/'scripts/locale-extra.tsv').read_text(encoding='utf-8').splitlines():
 if line:
  values=line.split('|');assert len(values)==6,values
  catalog[values[0]]=values
assert all(len(v)==6 and all(isinstance(s,str) and s for s in v) for v in catalog.values())
runtime=(ROOT/'scripts/i18n-runtime.js').read_text(encoding='utf-8')
(ROOT/'i18n.js').write_text('/* Generated by scripts/build_locales.py. */\n'+runtime.replace('/* CATALOG */{}',json.dumps(catalog,ensure_ascii=False,separators=(',',':'))),encoding='utf-8')
print('Compiled',len(catalog),'messages in six languages')
